//
//  MailIconNameKey.h
//  IF
//
//  Created by 马纵驰 on 15/10/10.
//
//

#ifndef MailIconNameKey_h
#define MailIconNameKey_h

#define MAILICONNAME_CHANNEL_ICON_FIGHT 		  			@"CHANNEL_ICON_FIGHT"
#define MAILICONNAME_CHANNEL_ICON_STUDIO        			@"CHANNEL_ICON_STUDIO"
#define MAILICONNAME_CHANNEL_ICON_SYSTEM        			@"CHANNEL_ICON_SYSTEM"
#define MAILICONNAME_CHANNEL_ICON_ALLIANCE      			@"CHANNEL_ICON_ALLIANCE"
#define MAILICONNAME_CHANNEL_ICON_MOD           			@"CHANNEL_ICON_MOD"
#define MAILICONNAME_CHANNEL_ICON_MESSAGE       			@"CHANNEL_ICON_MESSAGE"
#define MAILICONNAME_CHANNEL_ICON_ANNOUNCEMENT  			@"CHANNEL_ICON_ANNOUNCEMENT"
#define MAILICONNAME_CHANNEL_ICON_FAVORITE 	  			@"CHANNEL_ICON_FAVORITE"
#define MAILICONNAME_CHANNEL_ICON_MONSTER  				@"CHANNEL_ICON_MONSTER"
#define MAILICONNAME_CHANNEL_ICON_RESOURCE 	  			@"CHANNEL_ICON_RESOURCE"
#define MAILICONNAME_CHANNEL_ICON_EVENT 	  				@"CHANNEL_ICON_EVENT"


#define MAILICONNAME_MAIL_ICON_ANNOUNCEMENT				@"MAIL_ICON_ANNOUNCEMENT"
#define MAILICONNAME_MAIL_ICON_BATTLE_EXPLORE				@"MAIL_ICON_BATTLE_EXPLORE"
#define MAILICONNAME_MAIL_ICON_BATTLE_CAMP				@"MAIL_ICON_BATTLE_CAMP"
#define MAILICONNAME_MAIL_ICON_BATTLE_CAPTURE				@"MAIL_ICON_BATTLE_CAPTURE"
#define MAILICONNAME_MAIL_ICON_BATTLE_CITY_DEFENT_FAILURE	@"MAIL_ICON_BATTLE_CITY_DEFENT_FAILURE"
#define MAILICONNAME_MAIL_ICON_BATTLE_CITY_DEFENT_VICTORY	@"MAIL_ICON_BATTLE_CITY_DEFENT_VICTORY"
#define MAILICONNAME_MAIL_ICON_BATTLE_CITY_FAILURE 		@"MAIL_ICON_BATTLE_CITY_FAILURE"
#define MAILICONNAME_MAIL_ICON_BATTLE_CITY_VICTORY 		@"MAIL_ICON_BATTLE_CITY_VICTORY"
#define MAILICONNAME_MAIL_ICON_BATTLE_DETECT 				@"MAIL_ICON_BATTLE_DETECT"
#define MAILICONNAME_MAIL_ICON_BATTLE_KNIGHT 				@"MAIL_ICON_BATTLE_KNIGHT"
#define MAILICONNAME_MAIL_ICON_BATTLE_MONSTER 			@"MAIL_ICON_BATTLE_MONSTER"
#define MAILICONNAME_MAIL_ICON_BATTLE_REPORT 				@"MAIL_ICON_BATTLE_REPORT"
#define MAILICONNAME_MAIL_ICON_INVITE_JOIN_ALLIANCE 		@"MAIL_ICON_INVITE_JOIN_ALLIANCE"
#define MAILICONNAME_MAIL_ICON_INVITE_JOIN 				@"MAIL_ICON_INVITE_JOIN"
#define MAILICONNAME_MAIL_ICON_INVITE_KICKEDOUT 			@"MAIL_ICON_INVITE_KICKEDOUT"
#define MAILICONNAME_MAIL_ICON_INVITE_MOVE 				@"MAIL_ICON_INVITE_MOVE"
#define MAILICONNAME_MAIL_ICON_INVITE_REJECTED 			@"MAIL_ICON_INVITE_REJECTED"
#define MAILICONNAME_MAIL_ICON_STUDIO 					@"MAIL_ICON_STUDIO"
#define MAILICONNAME_MAIL_ICON_REWARD 					@"MAIL_ICON_REWARD"
#define MAILICONNAME_MAIL_ICON_SEARCH 					@"MAIL_ICON_SEARCH"
#define MAILICONNAME_MAIL_ICON_ID_BINGING 				@"MAIL_ICON_ID_BINGING"
#define MAILICONNAME_MAIL_ICON_SYSTEM  					@"MAIL_ICON_SYSTEM"
#define MAILICONNAME_MAIL_ICON_SYSTEM_VIP 				@"MAIL_ICON_SYSTEM_VIP"
#define MAILICONNAME_MAIL_ICON_CHAT_ROOM					@"MAIL_ICON_CHAT_ROOM"

#endif /* MailIconNameKey_h */
