LOCAL_C_INCLUDES := \
$(LOCAL_PATH)/../../IF/Classes \
$(LOCAL_PATH)/../../IF/Classes/controller \
$(LOCAL_PATH)/../../IF/Classes/Ext \
$(LOCAL_PATH)/../../IF/Classes/Ext/3dtouch \
$(LOCAL_PATH)/../../IF/Classes/Ext/3dtouch/playerInfo \
$(LOCAL_PATH)/../../IF/Classes/Ext/aes \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/ChartIOS \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/ChartIOS/category \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/ChartIOS/category/EGOImage \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/ChartIOS/category/EGOImage/EGOCache \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/ChartIOS/category/EGOImage/EGOImageLoader \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/ChartIOS/category/EGOImage/EGOImageView \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/ChartIOS/category/JsonToObj \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/ChartIOS/category/MJRefresh \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/ChartIOS/category/MJRefresh/Base \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/ChartIOS/category/MJRefresh/Custom \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/ChartIOS/category/MJRefresh/Custom/Footer \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/ChartIOS/category/MJRefresh/Custom/Footer/Auto \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/ChartIOS/category/MJRefresh/Custom/Footer/Back \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/ChartIOS/category/MJRefresh/Custom/Header \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/ChartIOS/category/MJRefresh/MJRefresh.bundle \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/ChartIOS/category/SlimeRefresh \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/ChartIOS/category/YiRefresh \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/ChartIOS/Controller \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/ChartIOS/Controller/groupChat \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/ChartIOS/Controller/mailList \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/ChartIOS/Controller/oneChat \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/ChartIOS/Controller/oneChat/chatCell \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/ChartIOS/Controller/PopUpController \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/ChartIOS/Controller/UITabelViewController \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/ChartIOS/Controller/UIViewController \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/ChartIOS/Host \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/ChartIOS/images \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/ChartIOS/model \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/ChartIOS/model/chatModel \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/ChartIOS/model/DB \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/ChartIOS/model/mail \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/ChartIOS/model/mail/allianceapply \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/ChartIOS/model/mail/allianceinvite \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/ChartIOS/model/mail/alliancekickout \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/ChartIOS/model/mail/battle \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/ChartIOS/model/mail/detectreport \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/ChartIOS/model/mail/inviteteleport \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/ChartIOS/model/mail/monster \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/ChartIOS/model/mail/ocupy \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/ChartIOS/model/mail/refuseallreply \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/ChartIOS/model/mail/resouce \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/ChartIOS/model/mail/resourcehelp \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/ChartIOS/model/mail/updatedata \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/ChartIOS/model/mail/worldboss \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/ChartIOS/model/mail/worldexplore \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/ChartIOS/view \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/ChartIOS/view/custemCell \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/CS_Debug \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/CS_Debug/chatservice_Debug \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/CS_Debug/chatservice_Debug/chatservice_Debug \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/CS_Debug/chatservice_Debug/chatservice_Debug/Assets.xcassets \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/CS_Debug/chatservice_Debug/chatservice_Debug/Assets.xcassets/222.imageset \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/CS_Debug/chatservice_Debug/chatservice_Debug/Assets.xcassets/[sysChat].imageset \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/CS_Debug/chatservice_Debug/chatservice_Debug/Assets.xcassets/AppIcon.appiconset \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/CS_Debug/chatservice_Debug/chatservice_Debug/Assets.xcassets/bubble_13 \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/CS_Debug/chatservice_Debug/chatservice_Debug/Assets.xcassets/bubble_13/aio_friend_bg_nor.imageset \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/CS_Debug/chatservice_Debug/chatservice_Debug/Assets.xcassets/bubble_13/aio_friend_bg_pressed.imageset \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/CS_Debug/chatservice_Debug/chatservice_Debug/Assets.xcassets/bubble_13/aio_friend_pic_nor.imageset \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/CS_Debug/chatservice_Debug/chatservice_Debug/Assets.xcassets/bubble_13/aio_friend_pic_pressed.imageset \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/CS_Debug/chatservice_Debug/chatservice_Debug/Assets.xcassets/bubble_13/aio_user_bg_dim.imageset \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/CS_Debug/chatservice_Debug/chatservice_Debug/Assets.xcassets/bubble_13/aio_user_bg_nor.imageset \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/CS_Debug/chatservice_Debug/chatservice_Debug/Assets.xcassets/bubble_13/aio_user_bg_pressed.imageset \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/CS_Debug/chatservice_Debug/chatservice_Debug/Assets.xcassets/bubble_13/aio_user_pic_nor.imageset \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/CS_Debug/chatservice_Debug/chatservice_Debug/Assets.xcassets/bubble_13/aio_user_pic_pressed.imageset \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/CS_Debug/chatservice_Debug/chatservice_Debug/Assets.xcassets/bubble_13/chat_avatar_icon.imageset \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/CS_Debug/chatservice_Debug/chatservice_Debug/Assets.xcassets/bubble_13/chat_avatar_impression_drawing.imageset \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/CS_Debug/chatservice_Debug/chatservice_Debug/Assets.xcassets/bubble_13/config.dataset \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/CS_Debug/chatservice_Debug/chatservice_Debug/Assets.xcassets/bubble_13/voice \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/CS_Debug/chatservice_Debug/chatservice_Debug/Assets.xcassets/bubble_13/voice/0001.imageset \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/CS_Debug/chatservice_Debug/chatservice_Debug/Assets.xcassets/bubble_13/voice/0002.imageset \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/CS_Debug/chatservice_Debug/chatservice_Debug/Assets.xcassets/bubble_13/voice/0003.imageset \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/CS_Debug/chatservice_Debug/chatservice_Debug/Assets.xcassets/bubble_13/voice/0004.imageset \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/CS_Debug/chatservice_Debug/chatservice_Debug/Assets.xcassets/bubble_13/voice/0005.imageset \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/CS_Debug/chatservice_Debug/chatservice_Debug/Assets.xcassets/bubble_13/voice/0006.imageset \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/CS_Debug/chatservice_Debug/chatservice_Debug/Assets.xcassets/bubble_13/voice/0007.imageset \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/CS_Debug/chatservice_Debug/chatservice_Debug/Assets.xcassets/bubble_13/voice/0008.imageset \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/CS_Debug/chatservice_Debug/chatservice_Debug/Assets.xcassets/bubble_13/voice/0009.imageset \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/CS_Debug/chatservice_Debug/chatservice_Debug/Assets.xcassets/bubble_13/voice/0010.imageset \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/CS_Debug/chatservice_Debug/chatservice_Debug/Assets.xcassets/bubble_13/voice/0011.imageset \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/CS_Debug/chatservice_Debug/chatservice_Debug/Assets.xcassets/bubble_13/voice/0012.imageset \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/CS_Debug/chatservice_Debug/chatservice_Debug/Assets.xcassets/bubble_13/voice/0013.imageset \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/CS_Debug/chatservice_Debug/chatservice_Debug/Assets.xcassets/bubble_13/voice/0014.imageset \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/CS_Debug/chatservice_Debug/chatservice_Debug/Assets.xcassets/bubble_13/voice/0015.imageset \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/CS_Debug/chatservice_Debug/chatservice_Debug/Assets.xcassets/bubble_13/voice/0016.imageset \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/CS_Debug/chatservice_Debug/chatservice_Debug/Assets.xcassets/bubble_13/voice/0017.imageset \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/CS_Debug/chatservice_Debug/chatservice_Debug/Assets.xcassets/bubble_13/voice/0018.imageset \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/CS_Debug/chatservice_Debug/chatservice_Debug/Assets.xcassets/bubble_13/voice/0019.imageset \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/CS_Debug/chatservice_Debug/chatservice_Debug/Assets.xcassets/bubble_13/voice/0020.imageset \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/CS_Debug/chatservice_Debug/chatservice_Debug/Assets.xcassets/csChatTableBackImage.imageset \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/CS_Debug/chatservice_Debug/chatservice_Debug/Assets.xcassets/head \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/CS_Debug/chatservice_Debug/chatservice_Debug/Assets.xcassets/head/g008.imageset \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/CS_Debug/chatservice_Debug/chatservice_Debug/Assets.xcassets/head/g012.imageset \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/CS_Debug/chatservice_Debug/chatservice_Debug/Assets.xcassets/head/g015.imageset \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/CS_Debug/chatservice_Debug/chatservice_Debug/Assets.xcassets/head/g017.imageset \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/CS_Debug/chatservice_Debug/chatservice_Debug/Assets.xcassets/head/g024.imageset \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/CS_Debug/chatservice_Debug/chatservice_Debug/Assets.xcassets/head/g026.imageset \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/CS_Debug/chatservice_Debug/chatservice_Debug/Assets.xcassets/head/g032.imageset \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/CS_Debug/chatservice_Debug/chatservice_Debug/Assets.xcassets/head/g038.imageset \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/CS_Debug/chatservice_Debug/chatservice_Debug/Assets.xcassets/head/g041.imageset \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/CS_Debug/chatservice_Debug/chatservice_Debug/Assets.xcassets/head/g044.imageset \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/CS_Debug/chatservice_Debug/chatservice_Debug/Assets.xcassets/head/g044_middle.imageset \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/CS_Debug/chatservice_Debug/chatservice_Debug/Assets.xcassets/head/g045.imageset \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/CS_Debug/chatservice_Debug/chatservice_Debug/Assets.xcassets/sendfailed.imageset \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/CS_Debug/chatservice_Debug/chatservice_Debug/Assets.xcassets/zzz.imageset \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/CS_Debug/chatservice_Debug/chatservice_Debug/Base.lproj \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/CS_Debug/chatservice_Debug/chatservice_Debug/Model \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/CS_Debug/chatservice_Debug/chatservice_Debug/view \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/CS_Debug/chatservice_Debug/chatservice_Debug.xcodeproj \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/CS_Debug/chatservice_Debug/chatservice_Debug.xcodeproj/project.xcworkspace \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/CS_Debug/chatservice_Debug/chatservice_DebugTests \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/CS_Debug/chatservice_Debug/chatservice_DebugUITests \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/Tools \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/Tools/AFNetworking \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/Tools/EMSDWebImage \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/Tools/EMSDWebImage/SlimeRefresh \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/Tools/JsonUtil \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/Tools/JsonUtil/JsonToObj \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/Tools/KZLInkLabel \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/Tools/LKDB \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/Tools/LKDB/FMDB \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/Tools/LKDB/FMDB/extra \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/Tools/LKDB/FMDB/src \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/Tools/LKDB/Helper \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/Tools/QBPopupMenu \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/Tools/RegexKitLite \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/Tools/SlimeRefresh \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/Tools/SocketRocket \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/Tools/YYKit \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/Tools/YYKit/Base \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/Tools/YYKit/Base/Foundation \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/Tools/YYKit/Base/Quartz \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/Tools/YYKit/Base/UIKit \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/Tools/YYKit/Cache \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/Tools/YYKit/Image \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/Tools/YYKit/Image/Categories \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/Tools/YYKit/Model \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/Tools/YYKit/Text \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/Tools/YYKit/Text/Component \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/Tools/YYKit/Text/String \
$(LOCAL_PATH)/../../IF/Classes/Ext/ChatService/Tools/YYKit/Utility \
$(LOCAL_PATH)/../../IF/Classes/Ext/des \
$(LOCAL_PATH)/../../IF/Classes/Ext/GUI \
$(LOCAL_PATH)/../../IF/Classes/Ext/GUI/CCRichLabel \
$(LOCAL_PATH)/../../IF/Classes/Ext/GUI/WebView \
$(LOCAL_PATH)/../../IF/Classes/Ext/utf8 \
$(LOCAL_PATH)/../../IF/Classes/lua \
$(LOCAL_PATH)/../../IF/Classes/model \
$(LOCAL_PATH)/../../IF/Classes/Net \
$(LOCAL_PATH)/../../IF/Classes/Net/command \
$(LOCAL_PATH)/../../IF/Classes/Net/command/alliance \
$(LOCAL_PATH)/../../IF/Classes/Net/push \
$(LOCAL_PATH)/../../IF/Classes/scene \
$(LOCAL_PATH)/../../IF/Classes/scene/battle \
$(LOCAL_PATH)/../../IF/Classes/scene/cropscene \
$(LOCAL_PATH)/../../IF/Classes/scene/loading \
$(LOCAL_PATH)/../../IF/Classes/scene/world \
$(LOCAL_PATH)/../../IF/Classes/view \
$(LOCAL_PATH)/../../IF/Classes/view/fogView \
$(LOCAL_PATH)/../../IF/Classes/view/guide \
$(LOCAL_PATH)/../../IF/Classes/view/guiExt \
$(LOCAL_PATH)/../../IF/Classes/view/popup \
$(LOCAL_PATH)/../../IF/Classes/view/popup/achievement \
$(LOCAL_PATH)/../../IF/Classes/view/popup/alliance \
$(LOCAL_PATH)/../../IF/Classes/view/popup/CrossServiceActivity \
$(LOCAL_PATH)/../../IF/Classes/view/popup/DailyActive \
$(LOCAL_PATH)/../../IF/Classes/view/popup/dragonBattle \
$(LOCAL_PATH)/../../IF/Classes/view/popup/kingdom \
$(LOCAL_PATH)/../../IF/Classes/view/popup/knight \
$(LOCAL_PATH)/../../IF/Classes/view/popup/Lottery \
$(LOCAL_PATH)/../../IF/Classes/view/popup/mail \
$(LOCAL_PATH)/../../IF/Classes/view/skill \
$(LOCAL_PATH)/../../IF/Classes/view/transition \
$(LOCAL_PATH)/../../IF/Classes/view/Widget \
$(LOCAL_PATH)/../../IF/libs/rapidxml \
$(LOCAL_PATH)/../../IF/libs/extensions \
$(LOCAL_PATH)/../../IF/libs/extensions/AdbertSDK \
$(LOCAL_PATH)/../../IF/libs/extensions/Appsflyer \
$(LOCAL_PATH)/../../IF/libs/extensions/GoogleConversionTrackingSDK \
$(LOCAL_PATH)/../../IF/libs/extensions/GoogleConversionTrackingSDK/Deprecated \
$(LOCAL_PATH)/../../IF/libs/extensions/GoogleConversionTrackingSDK/DoubleClick \
$(LOCAL_PATH)/../../IF/libs/extensions/libWeiboSDK \
$(LOCAL_PATH)/../../IF/libs/extensions/libWeiboSDK/WeiboSDK.bundle \
$(LOCAL_PATH)/../../IF/libs/extensions/libWeiboSDK/WeiboSDK.bundle/images \
$(LOCAL_PATH)/../../IF/libs/extensions/libWeiboSDK/WeiboSDK.bundle/others \

