LOCAL_SRC_FILES := main.cpp \
../../IF/Classes/AppDelegate.cpp \
../../IF/Classes/AppLibHelper.cpp \
../../IF/Classes/controller/AchievementController.cpp \
../../IF/Classes/controller/ActivityController.cpp \
../../IF/Classes/controller/AllianceDailyController.cpp \
../../IF/Classes/controller/AllianceManager.cpp \
../../IF/Classes/controller/ArmyController.cpp \
../../IF/Classes/controller/CCThreadManager.cpp \
../../IF/Classes/controller/ChatController.cpp \
../../IF/Classes/controller/DailyActiveController.cpp \
../../IF/Classes/controller/DeviceInfoController.cpp \
../../IF/Classes/controller/DynamicResourceController.cpp \
../../IF/Classes/controller/EnemyInfoController.cpp \
../../IF/Classes/controller/EquipmentController.cpp \
../../IF/Classes/controller/FriendsController.cpp \
../../IF/Classes/controller/FunBuildController.cpp \
../../IF/Classes/controller/GameController.cpp \
../../IF/Classes/controller/GCMRewardController.cpp \
../../IF/Classes/controller/GeneralManager.cpp \
../../IF/Classes/controller/GmController.cpp \
../../IF/Classes/controller/GuideController.cpp \
../../IF/Classes/controller/HFViewport.cpp \
../../IF/Classes/controller/KnightTitleController.cpp \
../../IF/Classes/controller/LocalController.cpp \
../../IF/Classes/controller/LotteryController.cpp \
../../IF/Classes/controller/LuaController.cpp \
../../IF/Classes/controller/MailController.cpp \
../../IF/Classes/controller/MazeController.cpp \
../../IF/Classes/controller/MiniMapController.cpp \
../../IF/Classes/controller/ModController.cpp \
../../IF/Classes/controller/NetController.cpp \
../../IF/Classes/controller/ParticleController.cpp \
../../IF/Classes/controller/PayController.cpp \
../../IF/Classes/controller/PlayerInfoController.cpp \
../../IF/Classes/controller/PopupViewController.cpp \
../../IF/Classes/controller/PrincessQuestController.cpp \
../../IF/Classes/controller/QuestController.cpp \
../../IF/Classes/controller/QueueController.cpp \
../../IF/Classes/controller/RewardController.cpp \
../../IF/Classes/controller/SceneController.cpp \
../../IF/Classes/controller/ScienceController.cpp \
../../IF/Classes/controller/ShakeController.cpp \
../../IF/Classes/controller/SocialController.cpp \
../../IF/Classes/controller/SoundController.cpp \
../../IF/Classes/controller/TimerController.cpp \
../../IF/Classes/controller/ToolController.cpp \
../../IF/Classes/controller/TroopsController.cpp \
../../IF/Classes/controller/UpdateManager.cpp \
../../IF/Classes/controller/UploadImageController.cpp \
../../IF/Classes/controller/WorldController.cpp \
../../IF/Classes/Ext/3dtouch/ThreeDTouchController.cpp \
../../IF/Classes/Ext/aes/aes.cpp \
../../IF/Classes/Ext/ArrowAni.cpp \
../../IF/Classes/Ext/CCAniNode.cpp \
../../IF/Classes/Ext/CCCommonUtils.cpp \
../../IF/Classes/Ext/CCDevice.cpp \
../../IF/Classes/Ext/CCEditText.cpp \
../../IF/Classes/Ext/CCGraySprite.cpp \
../../IF/Classes/Ext/CCINIParser.cpp \
../../IF/Classes/Ext/CCLoadSprite.cpp \
../../IF/Classes/Ext/CCMathUtils.cpp \
../../IF/Classes/Ext/CCProgressAppear.cpp \
../../IF/Classes/Ext/CCRapidXMLParser.cpp \
../../IF/Classes/Ext/CCSafeNotificationCenter.cpp \
../../IF/Classes/Ext/CCShake.cpp \
../../IF/Classes/Ext/CCTouchNode.cpp \
../../IF/Classes/Ext/CCXMLParser.cpp \
../../IF/Classes/Ext/ChatService/ChatServiceCocos2dx.cpp \
../../IF/Classes/Ext/ChatService/Tools/JsonUtil/CCJson.cpp \
../../IF/Classes/Ext/CheckBox.cpp \
../../IF/Classes/Ext/des/des.cpp \
../../IF/Classes/Ext/DTCursorTextField.cpp \
../../IF/Classes/Ext/GUI/CCBExtension.cpp \
../../IF/Classes/Ext/GUI/CCClipNode.cpp \
../../IF/Classes/Ext/GUI/CCColorSprite.cpp \
../../IF/Classes/Ext/GUI/CCEditBoxLoader.cpp \
../../IF/Classes/Ext/GUI/CCEditLabel.cpp \
../../IF/Classes/Ext/GUI/CCFlagWaveSprite.cpp \
../../IF/Classes/Ext/GUI/CCFloatingText.cpp \
../../IF/Classes/Ext/GUI/CCIFTouchNode.cpp \
../../IF/Classes/Ext/GUI/CCLabelBatch.cpp \
../../IF/Classes/Ext/GUI/CCLabelIF.cpp \
../../IF/Classes/Ext/GUI/CCLabelIFBMFont.cpp \
../../IF/Classes/Ext/GUI/CCLabelIFTTF.cpp \
../../IF/Classes/Ext/GUI/CCLineBatchedSprite.cpp \
../../IF/Classes/Ext/GUI/CCLineSprite.cpp \
../../IF/Classes/Ext/GUI/CCModelLayer.cpp \
../../IF/Classes/Ext/GUI/CCMultiColTableView.cpp \
../../IF/Classes/Ext/GUI/CCRichLabel/CCGradientSprite.cpp \
../../IF/Classes/Ext/GUI/CCRichLabel/CCImage_richlabel.cpp \
../../IF/Classes/Ext/GUI/CCRichLabel/CCMenuItemColor.cpp \
../../IF/Classes/Ext/GUI/CCRichLabel/CCRichLabelTTF.cpp \
../../IF/Classes/Ext/GUI/CCRichLabel/CCRichLabelTTFLinkStateSynchronizer.cpp \
../../IF/Classes/Ext/GUI/CCRichLabel/CCTexture2D_richlabel.cpp \
../../IF/Classes/Ext/GUI/CCRichLabel/CCTextureCache_richlabel.cpp \
../../IF/Classes/Ext/GUI/CCRichLabel/CLBitmapDC.cpp \
../../IF/Classes/Ext/GUI/CCRichLabel/org_cocos2dx_lib_CCImage_richlabel.cpp \
../../IF/Classes/Ext/GUI/CCRichLabel/VolatileTexture_richlabel.cpp \
../../IF/Classes/Ext/GUI/CCScrollLayer.cpp \
../../IF/Classes/Ext/GUI/CCTableViewTouchIFCell.cpp \
../../IF/Classes/Ext/GUI/ClippingNodeExt.cpp \
../../IF/Classes/Ext/GUI/FilterSprite.cpp \
../../IF/Classes/Ext/GUI/InputFieldMultiLine.cpp \
../../IF/Classes/Ext/GUI/SaoGuangEffectSprite.cpp \
../../IF/Classes/Ext/GUI/ScrollTableView.cpp \
../../IF/Classes/Ext/GUI/WebView/CCWebView.cpp \
../../IF/Classes/Ext/GUI/WebView/CCWebViewImpl.cpp \
../../IF/Classes/Ext/HandGuide.cpp \
../../IF/Classes/Ext/HFHeadImgNode.cpp \
../../IF/Classes/Ext/HFHttpClient.cpp \
../../IF/Classes/Ext/HFHttpResponse.cpp \
../../IF/Classes/Ext/HoolaiBISdkUtils.cpp \
../../IF/Classes/Ext/HoolaiSdkDelegate.cpp \
../../IF/Classes/Ext/IFCommonUtils.cpp \
../../IF/Classes/Ext/ShareSDKUtil.cpp \
../../IF/Classes/Ext/SNSUtil.cpp \
../../IF/Classes/Ext/SpriteBlur.cpp \
../../IF/Classes/Ext/SpriteSheetAni.cpp \
../../IF/Classes/Ext/Utf8Utils.cpp \
../../IF/Classes/lua/lua_cocos2dx_if_auto.cpp \
../../IF/Classes/lua/lua_cocos2dx_if_manual.cpp \
../../IF/Classes/model/AchievementInfo.cpp \
../../IF/Classes/model/ActivityEventInfo.cpp \
../../IF/Classes/model/ActivityEventObj.cpp \
../../IF/Classes/model/ActivityInfo.cpp \
../../IF/Classes/model/AllianceActivityInfo.cpp \
../../IF/Classes/model/AllianceDailyQuestInfo.cpp \
../../IF/Classes/model/AllianceDonateInfo.cpp \
../../IF/Classes/model/AllianceEventInfo.cpp \
../../IF/Classes/model/AllianceFightInfo.cpp \
../../IF/Classes/model/AllianceInfo.cpp \
../../IF/Classes/model/AllianceRankInfo.cpp \
../../IF/Classes/model/AllianceTeamInfo.cpp \
../../IF/Classes/model/AllianceTerritoryInfo.cpp \
../../IF/Classes/model/ArmyInfo.cpp \
../../IF/Classes/model/ChatInfo.cpp \
../../IF/Classes/model/ChatMailInfo.cpp \
../../IF/Classes/model/ChatShieldInfo.cpp \
../../IF/Classes/model/DailyActiveBoxInfo.cpp \
../../IF/Classes/model/DailyActiveItemInfo.cpp \
../../IF/Classes/model/DragonAllianceRankInfo.cpp \
../../IF/Classes/model/DragonRankInfo.cpp \
../../IF/Classes/model/EnemyInfo.cpp \
../../IF/Classes/model/EquipInfo.cpp \
../../IF/Classes/model/EquipmentInfo.cpp \
../../IF/Classes/model/FBFriendInfo.cpp \
../../IF/Classes/model/FirstPayInfo.cpp \
../../IF/Classes/model/FunBuildInfo.cpp \
../../IF/Classes/model/GCMRewardInfo.cpp \
../../IF/Classes/model/GeneralConfig.cpp \
../../IF/Classes/model/GeneralInfo.cpp \
../../IF/Classes/model/GlobalData.cpp \
../../IF/Classes/model/GoldExchangeItem.cpp \
../../IF/Classes/model/IFAllianceHelpReportInfo.cpp \
../../IF/Classes/model/KnightTitleInfo.cpp \
../../IF/Classes/model/LordInfo.cpp \
../../IF/Classes/model/MailConfig.cpp \
../../IF/Classes/model/MailCountObj.cpp \
../../IF/Classes/model/MailDialogInfo.cpp \
../../IF/Classes/model/MailHeiqishiCellInfo.cpp \
../../IF/Classes/model/MailHeiqishiInfo.cpp \
../../IF/Classes/model/MailInfo.cpp \
../../IF/Classes/model/MailMonsterCellInfo.cpp \
../../IF/Classes/model/MailMonsterInfo.cpp \
../../IF/Classes/model/MailResourceCellInfo.cpp \
../../IF/Classes/model/MailResourceHelpCellInfo.cpp \
../../IF/Classes/model/MailResourceHelpInfo.cpp \
../../IF/Classes/model/MailResourceInfo.cpp \
../../IF/Classes/model/MedalInfo.cpp \
../../IF/Classes/model/OfficeInfo.cpp \
../../IF/Classes/model/PlayerInfo.cpp \
../../IF/Classes/model/PlayerRankInfo.cpp \
../../IF/Classes/model/PrincessLimitedQuestInfo.cpp \
../../IF/Classes/model/PushSettingInfo.cpp \
../../IF/Classes/model/QuestInfo.cpp \
../../IF/Classes/model/QueueInfo.cpp \
../../IF/Classes/model/RankListInfo.cpp \
../../IF/Classes/model/ResourceInfo.cpp \
../../IF/Classes/model/SacrificeInfo.cpp \
../../IF/Classes/model/ScienceInfo.cpp \
../../IF/Classes/model/ScienceItemInfo.cpp \
../../IF/Classes/model/SearchInfo.cpp \
../../IF/Classes/model/ServerInfo.cpp \
../../IF/Classes/model/SettingObject.cpp \
../../IF/Classes/model/TileInfo.cpp \
../../IF/Classes/model/ToolInfo.cpp \
../../IF/Classes/model/TreatInfo.cpp \
../../IF/Classes/model/TypeDefinition.cpp \
../../IF/Classes/model/UserLvAboutInfo.cpp \
../../IF/Classes/model/UserPlatformInfo.cpp \
../../IF/Classes/model/YuanJunInfo.cpp \
../../IF/Classes/Net/command/AchieveGetCommand.cpp \
../../IF/Classes/Net/command/AchieveReceiveCommand.cpp \
../../IF/Classes/Net/command/ActExcCommand.cpp \
../../IF/Classes/Net/command/ActivityEventCommand.cpp \
../../IF/Classes/Net/command/ActivityScoreHistoryCommand.cpp \
../../IF/Classes/Net/command/ActPopTimesCommand.cpp \
../../IF/Classes/Net/command/AddDefenseCommand.cpp \
../../IF/Classes/Net/command/alliance/AcceptAllianceApplyCommand.cpp \
../../IF/Classes/Net/command/alliance/AllianceAcceptInviteCommand.cpp \
../../IF/Classes/Net/command/alliance/AllianceApplylistCommand.cpp \
../../IF/Classes/Net/command/alliance/AllianceCallHelpCommand.cpp \
../../IF/Classes/Net/command/alliance/AllianceCommentCheck.cpp \
../../IF/Classes/Net/command/alliance/AllianceCommentShieldAdd.cpp \
../../IF/Classes/Net/command/alliance/AllianceCommentShieldList.cpp \
../../IF/Classes/Net/command/alliance/AllianceCommentShieldRemove.cpp \
../../IF/Classes/Net/command/alliance/AllianceEventCommand.cpp \
../../IF/Classes/Net/command/alliance/AllianceFightBulletinCommand.cpp \
../../IF/Classes/Net/command/alliance/AllianceHelpAllCommand.cpp \
../../IF/Classes/Net/command/alliance/AllianceKickMemberCommand.cpp \
../../IF/Classes/Net/command/alliance/AllianceLeaderReplaceCommand.cpp \
../../IF/Classes/Net/command/alliance/AllianceLeaderTransCommand.cpp \
../../IF/Classes/Net/command/alliance/AllianceRallyListCommand.cpp \
../../IF/Classes/Net/command/alliance/AllianceReinforceSoldier.cpp \
../../IF/Classes/Net/command/alliance/AllianceRenderHelpCommand.cpp \
../../IF/Classes/Net/command/alliance/AllianceScienceCommand.cpp \
../../IF/Classes/Net/command/alliance/AllianceSendCommentCommand.cpp \
../../IF/Classes/Net/command/alliance/AllianceSetRankNameCommand.cpp \
../../IF/Classes/Net/command/alliance/AllianceShowHelpCommand.cpp \
../../IF/Classes/Net/command/alliance/ApplyAllianceCommand.cpp \
../../IF/Classes/Net/command/alliance/CancelAllianceApplyCommand.cpp \
../../IF/Classes/Net/command/alliance/CancelAllianceTeamCommand.cpp \
../../IF/Classes/Net/command/alliance/CancelInviteAllianceCommand.cpp \
../../IF/Classes/Net/command/alliance/ChangeAllianceAttributesCommand.cpp \
../../IF/Classes/Net/command/alliance/ChangeAllianceRankCommand.cpp \
../../IF/Classes/Net/command/alliance/ChangeAllianceRankDownCommand.cpp \
../../IF/Classes/Net/command/alliance/ChangeAllianceRankUpCommand.cpp \
../../IF/Classes/Net/command/alliance/ChangeRankCommand.cpp \
../../IF/Classes/Net/command/alliance/ChatIsInAllanceCommand.cpp \
../../IF/Classes/Net/command/alliance/CheckAllianceNameCommand.cpp \
../../IF/Classes/Net/command/alliance/checkAllianceRestrictcommamd.cpp \
../../IF/Classes/Net/command/alliance/CheckAllianceTagCommand.cpp \
../../IF/Classes/Net/command/alliance/CreateAllianceCommand.cpp \
../../IF/Classes/Net/command/alliance/DismissAllianceCommand.cpp \
../../IF/Classes/Net/command/alliance/GeAlliancetRankInfoCommand.cpp \
../../IF/Classes/Net/command/alliance/GetAllianceCommentsCommand.cpp \
../../IF/Classes/Net/command/alliance/GetAllianceListCommand.cpp \
../../IF/Classes/Net/command/alliance/GetAllianceMembersCommand.cpp \
../../IF/Classes/Net/command/alliance/GetAllianceRankCommand.cpp \
../../IF/Classes/Net/command/alliance/GetAllianceWarListCommand.cpp \
../../IF/Classes/Net/command/alliance/GetUserRankInfoCommand.cpp \
../../IF/Classes/Net/command/alliance/IFAllianceRankCmd.cpp \
../../IF/Classes/Net/command/alliance/InvitesAllianceCommand.cpp \
../../IF/Classes/Net/command/alliance/JoinAllianceCommand.cpp \
../../IF/Classes/Net/command/alliance/JoinAllianceTeamCommand.cpp \
../../IF/Classes/Net/command/alliance/LeaveAllianceCommand.cpp \
../../IF/Classes/Net/command/alliance/MemberInfo.cpp \
../../IF/Classes/Net/command/alliance/RecScienceAllianceCommand.cpp \
../../IF/Classes/Net/command/alliance/RefuseAllianceApplyCommand.cpp \
../../IF/Classes/Net/command/alliance/RefuseInviteCommand.cpp \
../../IF/Classes/Net/command/alliance/SearchUserAllianceCommand.cpp \
../../IF/Classes/Net/command/alliance/SetAllianceRankCommand.cpp \
../../IF/Classes/Net/command/alliance/UserApplyListCommand.cpp \
../../IF/Classes/Net/command/alliance/UserInviteListCommand.cpp \
../../IF/Classes/Net/command/alliance/YuanYunReturnCommand.cpp \
../../IF/Classes/Net/command/AllianceApplyInfoSendCommand.cpp \
../../IF/Classes/Net/command/AllianceDailyCommand.cpp \
../../IF/Classes/Net/command/AllianceDonateRankCommand.cpp \
../../IF/Classes/Net/command/AllianceShopShowCommand.cpp \
../../IF/Classes/Net/command/AllianceTerritoryShowCommand.cpp \
../../IF/Classes/Net/command/AllRankCommand.cpp \
../../IF/Classes/Net/command/AlPointFindCommand.cpp \
../../IF/Classes/Net/command/ArmyCancelCommand.cpp \
../../IF/Classes/Net/command/BuildingAddOutPutCommand.cpp \
../../IF/Classes/Net/command/BuyCityDefCommand.cpp \
../../IF/Classes/Net/command/BuyEnergyCommand.cpp \
../../IF/Classes/Net/command/BuyPicCommand.cpp \
../../IF/Classes/Net/command/CDkeyRewardCommand.cpp \
../../IF/Classes/Net/command/ChangeNickNameCommand.cpp \
../../IF/Classes/Net/command/ChangePicCommand.cpp \
../../IF/Classes/Net/command/ChangeSignSetCommand.cpp \
../../IF/Classes/Net/command/ChatLockCommand.cpp \
../../IF/Classes/Net/command/ChatLockInfoCommand.cpp \
../../IF/Classes/Net/command/ChatTestCommand.cpp \
../../IF/Classes/Net/command/ChatUnLockCommand.cpp \
../../IF/Classes/Net/command/CheckEmulatorCommand.cpp \
../../IF/Classes/Net/command/CheckNickNameCommand.cpp \
../../IF/Classes/Net/command/CityDefenceCommand.cpp \
../../IF/Classes/Net/command/CKFGetTopInfoCommand.cpp \
../../IF/Classes/Net/command/CKFNextRoundCommand.cpp \
../../IF/Classes/Net/command/CKFRewardInfoCommand.cpp \
../../IF/Classes/Net/command/CKFStreakListCommand.cpp \
../../IF/Classes/Net/command/CommandBase.cpp \
../../IF/Classes/Net/command/CountryChatCommand.cpp \
../../IF/Classes/Net/command/CreateChatRoomCommand.cpp \
../../IF/Classes/Net/command/CrossServerScoreCommand.cpp \
../../IF/Classes/Net/command/CrossServerStateLSCommand.cpp \
../../IF/Classes/Net/command/CrossServiceActivityCommand.cpp \
../../IF/Classes/Net/command/CSALeaveCommand.cpp \
../../IF/Classes/Net/command/DataRecordCommand.cpp \
../../IF/Classes/Net/command/DragonBattleAllianceInfoCommand.cpp \
../../IF/Classes/Net/command/DragonBattleAlliancePlayCommand.cpp \
../../IF/Classes/Net/command/DragonBattleApplyCommand.cpp \
../../IF/Classes/Net/command/DragonBattleApplyInfoCommand.cpp \
../../IF/Classes/Net/command/DragonBattleBuildingInfoCommand.cpp \
../../IF/Classes/Net/command/DragonBattleBulletinCommand.cpp \
../../IF/Classes/Net/command/DragonBattleEnterCommand.cpp \
../../IF/Classes/Net/command/DragonBattleFightRankCommand.cpp \
../../IF/Classes/Net/command/DragonBattleInfoCommand.cpp \
../../IF/Classes/Net/command/DragonBattleLeaveCommand.cpp \
../../IF/Classes/Net/command/DragonBattlePlayCommand.cpp \
../../IF/Classes/Net/command/DragonBattlePlayerInfoCommand.cpp \
../../IF/Classes/Net/command/DragonBattleRankCommand.cpp \
../../IF/Classes/Net/command/DragonBattleRewardInfoCommand.cpp \
../../IF/Classes/Net/command/DRConfigCommand.cpp \
../../IF/Classes/Net/command/EquipmentCommand.cpp \
../../IF/Classes/Net/command/FBCheckRequestCommand.cpp \
../../IF/Classes/Net/command/FBGetGlodMineCommand.cpp \
../../IF/Classes/Net/command/FBMineCallHelpCommand.cpp \
../../IF/Classes/Net/command/FBMineDigCommand.cpp \
../../IF/Classes/Net/command/FBMineFriendsCommand.cpp \
../../IF/Classes/Net/command/FBMineHelpCommand.cpp \
../../IF/Classes/Net/command/FBMineInviteCommand.cpp \
../../IF/Classes/Net/command/FBSendWorkerCommand.cpp \
../../IF/Classes/Net/command/FeedRecordCommand.cpp \
../../IF/Classes/Net/command/FeedRewardCommand.cpp \
../../IF/Classes/Net/command/fireandcomman.cpp \
../../IF/Classes/Net/command/FortCommand.cpp \
../../IF/Classes/Net/command/FreshRechargeCommand.cpp \
../../IF/Classes/Net/command/FriendsCommand.cpp \
../../IF/Classes/Net/command/FunBuildAllCommand.cpp \
../../IF/Classes/Net/command/FunBuildCommand.cpp \
../../IF/Classes/Net/command/GCMRewardCommand.cpp \
../../IF/Classes/Net/command/GeneralCommand.cpp \
../../IF/Classes/Net/command/GetActivityDetailCommand.cpp \
../../IF/Classes/Net/command/GetAllianceMemberPointCommand.cpp \
../../IF/Classes/Net/command/GetAllServerListCommand.cpp \
../../IF/Classes/Net/command/GetChatRoomListCommand.cpp \
../../IF/Classes/Net/command/GetChatRoomMemberCommand.cpp \
../../IF/Classes/Net/command/GetChatRoomMsgCommand.cpp \
../../IF/Classes/Net/command/GetFightOfKingRecord.cpp \
../../IF/Classes/Net/command/GetFriendListCommand.cpp \
../../IF/Classes/Net/command/GetInviteeCommand.cpp \
../../IF/Classes/Net/command/GetMsgBySeqIdCommand.cpp \
../../IF/Classes/Net/command/GetMultiUserInfoCommand.cpp \
../../IF/Classes/Net/command/GetNewMailMsgCommand.cpp \
../../IF/Classes/Net/command/GetNewMsgCommand.cpp \
../../IF/Classes/Net/command/GetNewSystemMailMsg_iOS_Command.cpp \
../../IF/Classes/Net/command/GetPowerInfoCommand.cpp \
../../IF/Classes/Net/command/GetStableEnergyCommand.cpp \
../../IF/Classes/Net/command/GetUpdateMailCommand.cpp \
../../IF/Classes/Net/command/GetUserInfoCommand.cpp \
../../IF/Classes/Net/command/GMCommand.cpp \
../../IF/Classes/Net/command/GoldExchangeInfoCommand.cpp \
../../IF/Classes/Net/command/GuideRecordCommand.cpp \
../../IF/Classes/Net/command/HoolaiBiCommand.cpp \
../../IF/Classes/Net/command/IFShakeCmd.cpp \
../../IF/Classes/Net/command/InitCommand.cpp \
../../IF/Classes/Net/command/InviteChatRoomMemberCommand.cpp \
../../IF/Classes/Net/command/InviteFBIdAcceptCommand.cpp \
../../IF/Classes/Net/command/InviteForGiftCommand.cpp \
../../IF/Classes/Net/command/InviteTeleportCommand.cpp \
../../IF/Classes/Net/command/KickChatRoomMemberCommand.cpp \
../../IF/Classes/Net/command/KingdomBannerCommand.cpp \
../../IF/Classes/Net/command/KingdomCheckNameCommand.cpp \
../../IF/Classes/Net/command/KingdomExecCommand.cpp \
../../IF/Classes/Net/command/KingdomKingChooseCommand.cpp \
../../IF/Classes/Net/command/KingdomOfficersCommand.cpp \
../../IF/Classes/Net/command/KingsGiftCommand.cpp \
../../IF/Classes/Net/command/KnightTitleCommand.cpp \
../../IF/Classes/Net/command/LoginCommand.cpp \
../../IF/Classes/Net/command/LogoutCommand.cpp \
../../IF/Classes/Net/command/LotteryActCommand.cpp \
../../IF/Classes/Net/command/LuaCommand.cpp \
../../IF/Classes/Net/command/MailBatchCommand.cpp \
../../IF/Classes/Net/command/MailBlockCommand.cpp \
../../IF/Classes/Net/command/MailDeleteAllCommand.cpp \
../../IF/Classes/Net/command/MailDeleteCommand.cpp \
../../IF/Classes/Net/command/MailFightReportCommand.cpp \
../../IF/Classes/Net/command/MailGetRewardCommand.cpp \
../../IF/Classes/Net/command/MailReadCommand.cpp \
../../IF/Classes/Net/command/MailSaveCommand.cpp \
../../IF/Classes/Net/command/MailSendCommand.cpp \
../../IF/Classes/Net/command/MineHelpInfoCommand.cpp \
../../IF/Classes/Net/command/MODCommand.cpp \
../../IF/Classes/Net/command/ModifyChatRoomNameCommand.cpp \
../../IF/Classes/Net/command/MonsterSiegeActivityInfoCommand.cpp \
../../IF/Classes/Net/command/MonsterSiegeRewardInfoCommand.cpp \
../../IF/Classes/Net/command/MonsterSiegeStartCommand.cpp \
../../IF/Classes/Net/command/PaymentCommand.cpp \
../../IF/Classes/Net/command/PhoneDeviceCommand.cpp \
../../IF/Classes/Net/command/PortActCommand.cpp \
../../IF/Classes/Net/command/PrincessRewardCommand.cpp \
../../IF/Classes/Net/command/PrincessTaskRewardCommand.cpp \
../../IF/Classes/Net/command/PromotionCommand.cpp \
../../IF/Classes/Net/command/PushRecordCommand.cpp \
../../IF/Classes/Net/command/PushSettingCommand.cpp \
../../IF/Classes/Net/command/QijiInfoCommand.cpp \
../../IF/Classes/Net/command/QuestRewardCommand.cpp \
../../IF/Classes/Net/command/QuestRewardInfoGetCommand.cpp \
../../IF/Classes/Net/command/QuestSubmitCommand.cpp \
../../IF/Classes/Net/command/QueueCommand.cpp \
../../IF/Classes/Net/command/QuitChatRoomArrayCommand.cpp \
../../IF/Classes/Net/command/QuitChatRoomCommand.cpp \
../../IF/Classes/Net/command/RebuildCommand.cpp \
../../IF/Classes/Net/command/ReportCustomHeadPicCommand.cpp \
../../IF/Classes/Net/command/ReportPlayChatCommand.cpp \
../../IF/Classes/Net/command/SacrificeCommand.cpp \
../../IF/Classes/Net/command/ScienceCommand.cpp \
../../IF/Classes/Net/command/SearchCommand.cpp \
../../IF/Classes/Net/command/SendChatRoomMsgCommand.cpp \
../../IF/Classes/Net/command/SendHeartCommand.cpp \
../../IF/Classes/Net/command/SettingXmlCommand.cpp \
../../IF/Classes/Net/command/ShowStatusItemCommand.cpp \
../../IF/Classes/Net/command/SqerSoldierRewardCommand.cpp \
../../IF/Classes/Net/command/SuggestionCommand.cpp \
../../IF/Classes/Net/command/TavernCommand.cpp \
../../IF/Classes/Net/command/ToolCommand.cpp \
../../IF/Classes/Net/command/TrainSoldierCommand.cpp \
../../IF/Classes/Net/command/TrainSoldiertimeCommand.cpp \
../../IF/Classes/Net/command/TrainSoldierWithCommand.cpp \
../../IF/Classes/Net/command/TranslateCommand.cpp \
../../IF/Classes/Net/command/TranslateOptimizeCommand.cpp \
../../IF/Classes/Net/command/TreatCommand.cpp \
../../IF/Classes/Net/command/TrialCommand.cpp \
../../IF/Classes/Net/command/TroopsCommand.cpp \
../../IF/Classes/Net/command/UnlockHiddenCityCommand.cpp \
../../IF/Classes/Net/command/UserBindCommand.cpp \
../../IF/Classes/Net/command/UserLevelCommand.cpp \
../../IF/Classes/Net/command/UseSkillCommand.cpp \
../../IF/Classes/Net/command/WinPointsUseCommand.cpp \
../../IF/Classes/Net/command/WorldActivityCommand.cpp \
../../IF/Classes/Net/command/WorldCommand.cpp \
../../IF/Classes/Net/command/WorldMarchCheck.cpp \
../../IF/Classes/Net/command/WorldSearchUserCommand.cpp \
../../IF/Classes/Net/push/AchieveCompletePush.cpp \
../../IF/Classes/Net/push/AchievementPush.cpp \
../../IF/Classes/Net/push/ActivityPush.cpp \
../../IF/Classes/Net/push/ActivityScorePush.cpp \
../../IF/Classes/Net/push/AdRewardPush.cpp \
../../IF/Classes/Net/push/AlliacnePushHelpNew.cpp \
../../IF/Classes/Net/push/AlliacnePushHelpUpdate.cpp \
../../IF/Classes/Net/push/AllianceApplyHandleNumPush.cpp \
../../IF/Classes/Net/push/AllianceApplyNumPush.cpp \
../../IF/Classes/Net/push/AllianceDismissPush.cpp \
../../IF/Classes/Net/push/AllianceEventPush.cpp \
../../IF/Classes/Net/push/AllianceJoinPush.cpp \
../../IF/Classes/Net/push/AllianceLeavelPush.cpp \
../../IF/Classes/Net/push/AllianceShopPush.cpp \
../../IF/Classes/Net/push/ArmyFoodPush.cpp \
../../IF/Classes/Net/push/ArmyInfoPush.cpp \
../../IF/Classes/Net/push/ArmyOpenPush.cpp \
../../IF/Classes/Net/push/BeenAttackedPush.cpp \
../../IF/Classes/Net/push/ChatPush.cpp \
../../IF/Classes/Net/push/ChatRoomMsgPush.cpp \
../../IF/Classes/Net/push/ChristmasPush.cpp \
../../IF/Classes/Net/push/CKFWarInfoPush.cpp \
../../IF/Classes/Net/push/CKFWarWinEndPush.cpp \
../../IF/Classes/Net/push/CKFWorldWarInfoPush.cpp \
../../IF/Classes/Net/push/CustomPicPush.cpp \
../../IF/Classes/Net/push/DailyActivePush.cpp \
../../IF/Classes/Net/push/DefencePush.cpp \
../../IF/Classes/Net/push/EmailConfirmPush.cpp \
../../IF/Classes/Net/push/EnemyReportPush.cpp \
../../IF/Classes/Net/push/EnergyPush.cpp \
../../IF/Classes/Net/push/EquipScrollPush.cpp \
../../IF/Classes/Net/push/ExplorePush.cpp \
../../IF/Classes/Net/push/FortOpenPush.cpp \
../../IF/Classes/Net/push/FreshRechargePush.cpp \
../../IF/Classes/Net/push/GeneralPush.cpp \
../../IF/Classes/Net/push/GeneralUpdateDataPush.cpp \
../../IF/Classes/Net/push/GoldExchangePush.cpp \
../../IF/Classes/Net/push/HoolaiBiPush.cpp \
../../IF/Classes/Net/push/HospitalReceivePush.cpp \
../../IF/Classes/Net/push/IFScoutPush.cpp \
../../IF/Classes/Net/push/ItemPush.cpp \
../../IF/Classes/Net/push/MailNewPush.cpp \
../../IF/Classes/Net/push/MailPush.cpp \
../../IF/Classes/Net/push/MerchantePush.cpp \
../../IF/Classes/Net/push/MineCallHelpPush.cpp \
../../IF/Classes/Net/push/MineHelpPush.cpp \
../../IF/Classes/Net/push/MODSetPush.cpp \
../../IF/Classes/Net/push/MonsterAttackPush.cpp \
../../IF/Classes/Net/push/PayPush.cpp \
../../IF/Classes/Net/push/PlayerInfoPush.cpp \
../../IF/Classes/Net/push/PrincessTaskPush.cpp \
../../IF/Classes/Net/push/PushAllianceActivityMsg.cpp \
../../IF/Classes/Net/push/PushAllianceFightBulletin.cpp \
../../IF/Classes/Net/push/PushAllianceLeaderTrans.cpp \
../../IF/Classes/Net/push/PushAllianceMarchSpd.cpp \
../../IF/Classes/Net/push/PushAllianceNum.cpp \
../../IF/Classes/Net/push/PushAllianceUpdate.cpp \
../../IF/Classes/Net/push/PushAssetsUpdate.cpp \
../../IF/Classes/Net/push/PushBase.cpp \
../../IF/Classes/Net/push/PushCKFTaskComplete.cpp \
../../IF/Classes/Net/push/PushCommonNotice.cpp \
../../IF/Classes/Net/push/PushDrangonBattleOccupy.cpp \
../../IF/Classes/Net/push/PushDrangonBattlePortChange.cpp \
../../IF/Classes/Net/push/PushGmNotice.cpp \
../../IF/Classes/Net/push/PushInit.cpp \
../../IF/Classes/Net/push/PushKingdomBanner.cpp \
../../IF/Classes/Net/push/PushKingdomKing.cpp \
../../IF/Classes/Net/push/PushKingdomName.cpp \
../../IF/Classes/Net/push/PushKingdomRes.cpp \
../../IF/Classes/Net/push/PushKingdomThroneOwne.cpp \
../../IF/Classes/Net/push/PushKingdomThroneOwnerCountdown.cpp \
../../IF/Classes/Net/push/PushKingdomThronePic.cpp \
../../IF/Classes/Net/push/PushKingdomWinner.cpp \
../../IF/Classes/Net/push/PushLeaveCrossServiceActivity.cpp \
../../IF/Classes/Net/push/PushPlayerAllianceRank.cpp \
../../IF/Classes/Net/push/QuestDataPush.cpp \
../../IF/Classes/Net/push/ResourceSpeedPush.cpp \
../../IF/Classes/Net/push/ResourcesPush.cpp \
../../IF/Classes/Net/push/SendHeartPush.cpp \
../../IF/Classes/Net/push/StaminaRollbackPush.cpp \
../../IF/Classes/Net/push/SystemUpdatePush.cpp \
../../IF/Classes/Net/push/TavernPush.cpp \
../../IF/Classes/Net/push/TerritoryBannerPush.cpp \
../../IF/Classes/Net/push/TerritoryInformationPush.cpp \
../../IF/Classes/Net/push/TerritoryResourcePush.cpp \
../../IF/Classes/Net/push/TerritoryTowerPush.cpp \
../../IF/Classes/Net/push/TerritoryWarehousePush.cpp \
../../IF/Classes/Net/push/UpBuildingsPush.cpp \
../../IF/Classes/Net/push/UserDataUpdatePush.cpp \
../../IF/Classes/Net/push/WorldActivityPush.cpp \
../../IF/Classes/Net/push/WorldMarchCompetePush.cpp \
../../IF/Classes/Net/push/WorldMarchPush.cpp \
../../IF/Classes/Net/push/WorldRefresh.cpp \
../../IF/Classes/scene/battle/BattleArmy.cpp \
../../IF/Classes/scene/battle/BattlefieldScene.cpp \
../../IF/Classes/scene/battle/BattleManager.cpp \
../../IF/Classes/scene/battle/BattleSoldier2.cpp \
../../IF/Classes/scene/battle/MainCityArmy.cpp \
../../IF/Classes/scene/battle/NewPlayerBattleScene.cpp \
../../IF/Classes/scene/battle/SoldierIconCell.cpp \
../../IF/Classes/scene/cropscene/BuildCCB.cpp \
../../IF/Classes/scene/cropscene/DragonFly.cpp \
../../IF/Classes/scene/cropscene/EagleCCB.cpp \
../../IF/Classes/scene/cropscene/FlyCell.cpp \
../../IF/Classes/scene/cropscene/FunBuild.cpp \
../../IF/Classes/scene/cropscene/FunBuildBtnsView.cpp \
../../IF/Classes/scene/cropscene/ImperialScene.cpp \
../../IF/Classes/scene/cropscene/Person.cpp \
../../IF/Classes/scene/cropscene/SpeBuild.cpp \
../../IF/Classes/scene/cropscene/SpeBuildBtnsView.cpp \
../../IF/Classes/scene/cropscene/TalkNoticeCell.cpp \
../../IF/Classes/scene/cropscene/WallBuild.cpp \
../../IF/Classes/scene/loading/LoadingScene.cpp \
../../IF/Classes/scene/SceneContainer.cpp \
../../IF/Classes/scene/world/AAreaBuildCCB.cpp \
../../IF/Classes/scene/world/ActBossPopUp.cpp \
../../IF/Classes/scene/world/AddFavorite.cpp \
../../IF/Classes/scene/world/AllianceAreaPopupView.cpp \
../../IF/Classes/scene/world/BaseTileInfo.cpp \
../../IF/Classes/scene/world/BlankTile.cpp \
../../IF/Classes/scene/world/CityCrashView.cpp \
../../IF/Classes/scene/world/CrossServerMoveCityPopUpView.cpp \
../../IF/Classes/scene/world/DragonBuildingTile.cpp \
../../IF/Classes/scene/world/FavoriteList.cpp \
../../IF/Classes/scene/world/IFAddMonsterLayer.cpp \
../../IF/Classes/scene/world/IFAddTowerPopup.cpp \
../../IF/Classes/scene/world/IFMapMaskLayer.cpp \
../../IF/Classes/scene/world/IFShakeGuideLayer.cpp \
../../IF/Classes/scene/world/IFShakeLayer.cpp \
../../IF/Classes/scene/world/KingBattleRankView.cpp \
../../IF/Classes/scene/world/KingBattleRewardView.cpp \
../../IF/Classes/scene/world/MainCityTile.cpp \
../../IF/Classes/scene/world/MarchDetailView.cpp \
../../IF/Classes/scene/world/MinimapLocalView.cpp \
../../IF/Classes/scene/world/MinimapUIAreaView.cpp \
../../IF/Classes/scene/world/MinimapUIView.cpp \
../../IF/Classes/scene/world/MinimapView.cpp \
../../IF/Classes/scene/world/MinimapViewCCB.cpp \
../../IF/Classes/scene/world/MonsterDetailView.cpp \
../../IF/Classes/scene/world/MonsterTile.cpp \
../../IF/Classes/scene/world/MoveCityPopUpView.cpp \
../../IF/Classes/scene/world/MoveToView.cpp \
../../IF/Classes/scene/world/NewBaseTileInfo.cpp \
../../IF/Classes/scene/world/NewResourceTile.cpp \
../../IF/Classes/scene/world/NewWorldMarchArmy.cpp \
../../IF/Classes/scene/world/PlayerTile.cpp \
../../IF/Classes/scene/world/ResourceTile.cpp \
../../IF/Classes/scene/world/ResourceTileInfoPopUpView.cpp \
../../IF/Classes/scene/world/ScoutInfo.cpp \
../../IF/Classes/scene/world/ServerListPopUpView.cpp \
../../IF/Classes/scene/world/SuperMinePopupView.cpp \
../../IF/Classes/scene/world/TerritoryBannerPopupView.cpp \
../../IF/Classes/scene/world/TerritoryBannerTile.cpp \
../../IF/Classes/scene/world/TerritoryResourceTile.cpp \
../../IF/Classes/scene/world/TerritoryTile.cpp \
../../IF/Classes/scene/world/TerritoryTowerTile.cpp \
../../IF/Classes/scene/world/TerritoryWarehouseTile.cpp \
../../IF/Classes/scene/world/ThroneTile.cpp \
../../IF/Classes/scene/world/TrebuchetTile.cpp \
../../IF/Classes/scene/world/TroopBuildingDetailView.cpp \
../../IF/Classes/scene/world/TroopInformationView.cpp \
../../IF/Classes/scene/world/WareHousePopupView.cpp \
../../IF/Classes/scene/world/WildMonsterPopUp.cpp \
../../IF/Classes/scene/world/WorldMapView.cpp \
../../IF/Classes/scene/world/WorldResGetView.cpp \
../../IF/Classes/view/fogView/TiledFourCell.cpp \
../../IF/Classes/view/guide/GuidePlotView.cpp \
../../IF/Classes/view/guide/GuideView.cpp \
../../IF/Classes/view/guide/NewPlotView.cpp \
../../IF/Classes/view/guiExt/ArcScrollView.cpp \
../../IF/Classes/view/guiExt/CCSliderBar.cpp \
../../IF/Classes/view/guiExt/CCStarBar.cpp \
../../IF/Classes/view/guiExt/DropRdCCB.cpp \
../../IF/Classes/view/guiExt/DropSacrificeAnim.cpp \
../../IF/Classes/view/guiExt/FlyCBuildView.cpp \
../../IF/Classes/view/guiExt/HFUrlImage.cpp \
../../IF/Classes/view/guiExt/HFUrlImageCache.cpp \
../../IF/Classes/view/guiExt/LoadWebImg.cpp \
../../IF/Classes/view/guiExt/md5.cpp \
../../IF/Classes/view/guiExt/NpcTalkView.cpp \
../../IF/Classes/view/guiExt/TransitionCloud.cpp \
../../IF/Classes/view/guiExt/TransitionLayer.cpp \
../../IF/Classes/view/popup/AchieveFinishView.cpp \
../../IF/Classes/view/popup/achievement/AchievementNewView.cpp \
../../IF/Classes/view/popup/achievement/MedalNewView.cpp \
../../IF/Classes/view/popup/AchievementDetailPopUpView.cpp \
../../IF/Classes/view/popup/AchievementNewPopUpView.cpp \
../../IF/Classes/view/popup/ActivityBeginView.cpp \
../../IF/Classes/view/popup/ActivityDetailView.cpp \
../../IF/Classes/view/popup/ActivityExcView.cpp \
../../IF/Classes/view/popup/ActivityHistoryView.cpp \
../../IF/Classes/view/popup/ActivityListAdView.cpp \
../../IF/Classes/view/popup/ActivityListView.cpp \
../../IF/Classes/view/popup/ActivityPopupView.cpp \
../../IF/Classes/view/popup/ActivityRankReward.cpp \
../../IF/Classes/view/popup/ActivityRewardView.cpp \
../../IF/Classes/view/popup/ActivityTipView.cpp \
../../IF/Classes/view/popup/ActivityView.cpp \
../../IF/Classes/view/popup/alliance/AddAllianceTipsView.cpp \
../../IF/Classes/view/popup/alliance/AlertAddAllianceView.cpp \
../../IF/Classes/view/popup/alliance/AllianceActBossView.cpp \
../../IF/Classes/view/popup/alliance/AllianceActivityRewardView.cpp \
../../IF/Classes/view/popup/alliance/AllianceActivityView.cpp \
../../IF/Classes/view/popup/alliance/AllianceApplyInfoView.cpp \
../../IF/Classes/view/popup/alliance/AllianceApplyMessageView.cpp \
../../IF/Classes/view/popup/alliance/AllianceApplyView.cpp \
../../IF/Classes/view/popup/alliance/AllianceCheckView.cpp \
../../IF/Classes/view/popup/alliance/AllianceCommentView.cpp \
../../IF/Classes/view/popup/alliance/AllianceDailyPublishView.cpp \
../../IF/Classes/view/popup/alliance/AllianceDonateRankView.cpp \
../../IF/Classes/view/popup/alliance/AllianceEditAnnounceView.cpp \
../../IF/Classes/view/popup/alliance/AllianceFlagPar.cpp \
../../IF/Classes/view/popup/alliance/AllianceFunView.cpp \
../../IF/Classes/view/popup/alliance/AllianceHelpView.cpp \
../../IF/Classes/view/popup/alliance/AllianceInfoMembersView.cpp \
../../IF/Classes/view/popup/alliance/AllianceInfoView.cpp \
../../IF/Classes/view/popup/alliance/AllianceIntroTip.cpp \
../../IF/Classes/view/popup/alliance/AllianceInviteView.cpp \
../../IF/Classes/view/popup/alliance/AllianceManagerFunView.cpp \
../../IF/Classes/view/popup/alliance/AllianceMarketView.cpp \
../../IF/Classes/view/popup/alliance/AllianceMassTeamView.cpp \
../../IF/Classes/view/popup/alliance/AllianceRankAttrView.cpp \
../../IF/Classes/view/popup/alliance/AllianceRankView.cpp \
../../IF/Classes/view/popup/alliance/AllianceResourceTradeView.cpp \
../../IF/Classes/view/popup/alliance/AllianceScienceClassView.cpp \
../../IF/Classes/view/popup/alliance/AllianceScienceDonateView.cpp \
../../IF/Classes/view/popup/alliance/AllianceScienceHistoryView.cpp \
../../IF/Classes/view/popup/alliance/AllianceScienceListView.cpp \
../../IF/Classes/view/popup/alliance/AllianceScienceTreeView.cpp \
../../IF/Classes/view/popup/alliance/AllianceScienceView.cpp \
../../IF/Classes/view/popup/alliance/AllianceShopView.cpp \
../../IF/Classes/view/popup/alliance/AllianceTerritoryView.cpp \
../../IF/Classes/view/popup/alliance/AllianceTitleRankCell.cpp \
../../IF/Classes/view/popup/alliance/AllianceUnlockView.cpp \
../../IF/Classes/view/popup/alliance/AllianceWarDetailView.cpp \
../../IF/Classes/view/popup/alliance/AllianceWarHeadCell.cpp \
../../IF/Classes/view/popup/alliance/AllianceWarResultView.cpp \
../../IF/Classes/view/popup/alliance/AllianceWarView.cpp \
../../IF/Classes/view/popup/alliance/ChangeAllianceFlagView.cpp \
../../IF/Classes/view/popup/alliance/CheckAllianceInfoView.cpp \
../../IF/Classes/view/popup/alliance/CreateAllianceView.cpp \
../../IF/Classes/view/popup/alliance/IFAllianceHelpReportLayer.cpp \
../../IF/Classes/view/popup/alliance/IFAllianceShakeLayer.cpp \
../../IF/Classes/view/popup/alliance/IFPanelLayer.cpp \
../../IF/Classes/view/popup/alliance/IFResourceLayer.cpp \
../../IF/Classes/view/popup/alliance/JoinAllianceView.cpp \
../../IF/Classes/view/popup/alliance/JoinRecAllianceTipView.cpp \
../../IF/Classes/view/popup/alliance/PlayerRankListView.cpp \
../../IF/Classes/view/popup/alliance/TerritoryBannerChoseView.cpp \
../../IF/Classes/view/popup/alliance/TerritoryFunctionView.cpp \
../../IF/Classes/view/popup/alliance/TerritoryInfoDetailView.cpp \
../../IF/Classes/view/popup/alliance/TerritoryInformationView.cpp \
../../IF/Classes/view/popup/alliance/TerritoryResourceDetailView.cpp \
../../IF/Classes/view/popup/alliance/TerritoryTowerTipsView.cpp \
../../IF/Classes/view/popup/alliance/TerritoryUnlockTipsView.cpp \
../../IF/Classes/view/popup/alliance/TerritoryWarehouseDetailView.cpp \
../../IF/Classes/view/popup/alliance/TerritoryWarehouseView.cpp \
../../IF/Classes/view/popup/alliance/UpdateAllianceInfoView.cpp \
../../IF/Classes/view/popup/alliance/YuanJunDetailView.cpp \
../../IF/Classes/view/popup/alliance/YuanJunView.cpp \
../../IF/Classes/view/popup/AllianceAni.cpp \
../../IF/Classes/view/popup/AllianceMoveCityConfirmView.cpp \
../../IF/Classes/view/popup/AllRankListCell.cpp \
../../IF/Classes/view/popup/AllRankListPopUpView.cpp \
../../IF/Classes/view/popup/ArcPopupBaseView.cpp \
../../IF/Classes/view/popup/BackpackView.cpp \
../../IF/Classes/view/popup/BanTimeView.cpp \
../../IF/Classes/view/popup/BatchBuyItemView.cpp \
../../IF/Classes/view/popup/BattleReportMailPopUpView.cpp \
../../IF/Classes/view/popup/BattleReportMailResPopUpView.cpp \
../../IF/Classes/view/popup/BattleView.cpp \
../../IF/Classes/view/popup/BattleWinOrLoseInfo.cpp \
../../IF/Classes/view/popup/BuildingHospitalPopUpView.cpp \
../../IF/Classes/view/popup/BuildListView.cpp \
../../IF/Classes/view/popup/BuildMoreInfoView.cpp \
../../IF/Classes/view/popup/BuildQueueCell.cpp \
../../IF/Classes/view/popup/BuildQueueView.cpp \
../../IF/Classes/view/popup/BuildUpgradeView.cpp \
../../IF/Classes/view/popup/ButtonLightEffect.cpp \
../../IF/Classes/view/popup/CaptchaView.cpp \
../../IF/Classes/view/popup/CDkeyPopUpView.cpp \
../../IF/Classes/view/popup/ChangeNickNameView.cpp \
../../IF/Classes/view/popup/ChangePicView.cpp \
../../IF/Classes/view/popup/ChangeServerView.cpp \
../../IF/Classes/view/popup/ChatCell.cpp \
../../IF/Classes/view/popup/ChatRoomCell.cpp \
../../IF/Classes/view/popup/ChatRoomView.cpp \
../../IF/Classes/view/popup/ChatView.cpp \
../../IF/Classes/view/popup/ChestUseView.cpp \
../../IF/Classes/view/popup/ChestUseViewCell.cpp \
../../IF/Classes/view/popup/ChooseUserView.cpp \
../../IF/Classes/view/popup/CityDefenseView.cpp \
../../IF/Classes/view/popup/ComposeAni.cpp \
../../IF/Classes/view/popup/ComposeView.cpp \
../../IF/Classes/view/popup/ConfirmDialogView.cpp \
../../IF/Classes/view/popup/CountryChooseFlagView.cpp \
../../IF/Classes/view/popup/CrossServiceActivity/CrossServiceActivityView.cpp \
../../IF/Classes/view/popup/CrossServiceActivity/CrossServiceRankView.cpp \
../../IF/Classes/view/popup/CrossServiceActivity/CrossServiceTargetView.cpp \
../../IF/Classes/view/popup/CrossServiceActivity/CSAWorldBtn.cpp \
../../IF/Classes/view/popup/CrossServiceActivity/LianShengView.cpp \
../../IF/Classes/view/popup/DailyActive/AllianceScoreActiveView.cpp \
../../IF/Classes/view/popup/DailyActive/CountryScoreActiveView.cpp \
../../IF/Classes/view/popup/DailyActive/DailyActiveBoxInfoView.cpp \
../../IF/Classes/view/popup/DailyActive/DailyActiveView.cpp \
../../IF/Classes/view/popup/DailyActive/NewPlayerQianDaoView.cpp \
../../IF/Classes/view/popup/DailyActive/ScoreTableView.cpp \
../../IF/Classes/view/popup/DailyActive/SingleScoreActiveView.cpp \
../../IF/Classes/view/popup/DailyActive/SingleScoreHistoryRankView.cpp \
../../IF/Classes/view/popup/DailyActive/SingleScoreRankView.cpp \
../../IF/Classes/view/popup/DailyActive/SingleScoreWaiteView.cpp \
../../IF/Classes/view/popup/DailyActive/TrainingView.cpp \
../../IF/Classes/view/popup/DailyRwdView.cpp \
../../IF/Classes/view/popup/DefaultTableViewDelegate.cpp \
../../IF/Classes/view/popup/DetectMailPopUpView.cpp \
../../IF/Classes/view/popup/dragonBattle/AgainstInfoView.cpp \
../../IF/Classes/view/popup/dragonBattle/DragonBattleJoinView.cpp \
../../IF/Classes/view/popup/dragonBattle/DragonBattlePrizeView.cpp \
../../IF/Classes/view/popup/dragonBattle/DragonBattleRewardView.cpp \
../../IF/Classes/view/popup/dragonBattle/DragonBattleWarListView.cpp \
../../IF/Classes/view/popup/dragonBattle/DragonHistoryView.cpp \
../../IF/Classes/view/popup/dragonBattle/DragonManageView.cpp \
../../IF/Classes/view/popup/dragonBattle/DragonPrizeGetView.cpp \
../../IF/Classes/view/popup/dragonBattle/DragonStatisticsView.cpp \
../../IF/Classes/view/popup/dragonBattle/DragonZhenYingView.cpp \
../../IF/Classes/view/popup/EnemyInfoMoreView.cpp \
../../IF/Classes/view/popup/EquipComposeView.cpp \
../../IF/Classes/view/popup/EquipFinishView.cpp \
../../IF/Classes/view/popup/EquipInfoView.cpp \
../../IF/Classes/view/popup/EquipLongjingView.cpp \
../../IF/Classes/view/popup/EquipMeltView.cpp \
../../IF/Classes/view/popup/EquipmentBagView.cpp \
../../IF/Classes/view/popup/EquipmentCreateView.cpp \
../../IF/Classes/view/popup/EquipmentListView.cpp \
../../IF/Classes/view/popup/EquipNewUseView.cpp \
../../IF/Classes/view/popup/EquipSiteView.cpp \
../../IF/Classes/view/popup/EvaluationView.cpp \
../../IF/Classes/view/popup/ExplorePopUpView.cpp \
../../IF/Classes/view/popup/FireSoldierView.cpp \
../../IF/Classes/view/popup/FlyHint.cpp \
../../IF/Classes/view/popup/FlyRewardPic.cpp \
../../IF/Classes/view/popup/FlyRollingText.cpp \
../../IF/Classes/view/popup/FlySystemUpdateHint.cpp \
../../IF/Classes/view/popup/FreeListView.cpp \
../../IF/Classes/view/popup/FreshRechargeView.cpp \
../../IF/Classes/view/popup/FriendSearch.cpp \
../../IF/Classes/view/popup/FriendsView.cpp \
../../IF/Classes/view/popup/FunBuildView.cpp \
../../IF/Classes/view/popup/GeneralBodySprite.cpp \
../../IF/Classes/view/popup/GeneralHeadPic.cpp \
../../IF/Classes/view/popup/GeneralSkillListPopUpView.cpp \
../../IF/Classes/view/popup/GeneralsPopupView.cpp \
../../IF/Classes/view/popup/GoldExchangeAdvertisingView_NEW.cpp \
../../IF/Classes/view/popup/GoldExchangeItemView_NEW.cpp \
../../IF/Classes/view/popup/GoldExchangeMoreListView.cpp \
../../IF/Classes/view/popup/GoldExchangeSaleView.cpp \
../../IF/Classes/view/popup/GoldExchangeView_NEW.cpp \
../../IF/Classes/view/popup/HarvestSkillAni.cpp \
../../IF/Classes/view/popup/HelpView.cpp \
../../IF/Classes/view/popup/HongBaoGetView.cpp \
../../IF/Classes/view/popup/HongBaoUseView.cpp \
../../IF/Classes/view/popup/HowToPlayCell.cpp \
../../IF/Classes/view/popup/HowToPlayView.cpp \
../../IF/Classes/view/popup/HtmlLabelTFNode.cpp \
../../IF/Classes/view/popup/IFGoogleTip.cpp \
../../IF/Classes/view/popup/IFSupermanTip.cpp \
../../IF/Classes/view/popup/InnerSettingView.cpp \
../../IF/Classes/view/popup/InviteForGiftView.cpp \
../../IF/Classes/view/popup/ItemStatusView.cpp \
../../IF/Classes/view/popup/kingdom/CheckKingdomView.cpp \
../../IF/Classes/view/popup/kingdom/KingChangePalaceView.cpp \
../../IF/Classes/view/popup/kingdom/KingdomAppointView.cpp \
../../IF/Classes/view/popup/kingdom/KingdomMailView.cpp \
../../IF/Classes/view/popup/kingdom/KingdomNameChangeView.cpp \
../../IF/Classes/view/popup/kingdom/KingdomOfficalsCell.cpp \
../../IF/Classes/view/popup/kingdom/KingdomRemoveAppointView.cpp \
../../IF/Classes/view/popup/kingdom/KingdomServantCell.cpp \
../../IF/Classes/view/popup/kingdom/KingdomThroneActivityView.cpp \
../../IF/Classes/view/popup/kingdom/KingsGiftView.cpp \
../../IF/Classes/view/popup/kingdom/ManagerKingdomView.cpp \
../../IF/Classes/view/popup/knight/BedgeComposeView.cpp \
../../IF/Classes/view/popup/knight/KnightListView.cpp \
../../IF/Classes/view/popup/knight/KnightTitileView.cpp \
../../IF/Classes/view/popup/KoreaPermitPopUPView.cpp \
../../IF/Classes/view/popup/LanguageSettingUtil.cpp \
../../IF/Classes/view/popup/LanguageSettingView.cpp \
../../IF/Classes/view/popup/LoginServiceView.cpp \
../../IF/Classes/view/popup/LongJingBuyView.cpp \
../../IF/Classes/view/popup/LongJingStoreView.cpp \
../../IF/Classes/view/popup/Lottery/LotteryAct2ShowView.cpp \
../../IF/Classes/view/popup/Lottery/LotteryAct2View.cpp \
../../IF/Classes/view/popup/Lottery/LotteryActView.cpp \
../../IF/Classes/view/popup/Lottery/LotteryRotateView.cpp \
../../IF/Classes/view/popup/LuaInterface.cpp \
../../IF/Classes/view/popup/mail/MailCell.cpp \
../../IF/Classes/view/popup/mail/MailPopUpView.cpp \
../../IF/Classes/view/popup/mail/MailReadPopUpView.cpp \
../../IF/Classes/view/popup/mail/MailWritePopUpView.cpp \
../../IF/Classes/view/popup/MailAnnouncePopUp.cpp \
../../IF/Classes/view/popup/MailBattleDetailView.cpp \
../../IF/Classes/view/popup/MailDialogView.cpp \
../../IF/Classes/view/popup/MailGiftView.cpp \
../../IF/Classes/view/popup/MailHeiqishiListView.cpp \
../../IF/Classes/view/popup/MailMonsterListView.cpp \
../../IF/Classes/view/popup/MailResourceHelpView.cpp \
../../IF/Classes/view/popup/MailResourcePopUpView.cpp \
../../IF/Classes/view/popup/MailSystemCell.cpp \
../../IF/Classes/view/popup/MailSystemListPopUp.cpp \
../../IF/Classes/view/popup/MainCityMoreView.cpp \
../../IF/Classes/view/popup/MainCityView.cpp \
../../IF/Classes/view/popup/MakingSoldierView.cpp \
../../IF/Classes/view/popup/MarchFormationView.cpp \
../../IF/Classes/view/popup/MateCreateView.cpp \
../../IF/Classes/view/popup/MatetialAni.cpp \
../../IF/Classes/view/popup/MerchantView.cpp \
../../IF/Classes/view/popup/MiraOpenView.cpp \
../../IF/Classes/view/popup/MODContactView.cpp \
../../IF/Classes/view/popup/MODView.cpp \
../../IF/Classes/view/popup/MonsterAttackPopUpView.cpp \
../../IF/Classes/view/popup/MonthCardView.cpp \
../../IF/Classes/view/popup/MoveBuildView.cpp \
../../IF/Classes/view/popup/NewEnemyInfoMoreView.cpp \
../../IF/Classes/view/popup/NewTroopsView.cpp \
../../IF/Classes/view/popup/NoticeView.cpp \
../../IF/Classes/view/popup/OccupyMailPopUpView.cpp \
../../IF/Classes/view/popup/ParticleFireAni.cpp \
../../IF/Classes/view/popup/PermitionForServicePopupView.cpp \
../../IF/Classes/view/popup/PlayerInfoBtnPopUpView.cpp \
../../IF/Classes/view/popup/PopupBaseView.cpp \
../../IF/Classes/view/popup/PortActView.cpp \
../../IF/Classes/view/popup/PrincessQuestDetailView.cpp \
../../IF/Classes/view/popup/PrincessQuestView.cpp \
../../IF/Classes/view/popup/ProductionSoldiersView.cpp \
../../IF/Classes/view/popup/PropSpeedupView.cpp \
../../IF/Classes/view/popup/PushSettingView.cpp \
../../IF/Classes/view/popup/RechargeACTVCell.cpp \
../../IF/Classes/view/popup/RechargePopupView.cpp \
../../IF/Classes/view/popup/RepayView.cpp \
../../IF/Classes/view/popup/ResourceMailPopUpView.cpp \
../../IF/Classes/view/popup/RGBTest.cpp \
../../IF/Classes/view/popup/RoleInfoView.cpp \
../../IF/Classes/view/popup/RollingText.cpp \
../../IF/Classes/view/popup/SacrificePopUpView.cpp \
../../IF/Classes/view/popup/ScienceListView.cpp \
../../IF/Classes/view/popup/ScienceView.cpp \
../../IF/Classes/view/popup/Search.cpp \
../../IF/Classes/view/popup/ServerLsitCell.cpp \
../../IF/Classes/view/popup/ServerUpdateView.cpp \
../../IF/Classes/view/popup/SetAccountView.cpp \
../../IF/Classes/view/popup/SettingPopUpView.cpp \
../../IF/Classes/view/popup/ShieldUnlockPopUpView.cpp \
../../IF/Classes/view/popup/SkinListView.cpp \
../../IF/Classes/view/popup/SocialPopUpView.cpp \
../../IF/Classes/view/popup/SoldierInfoView.cpp \
../../IF/Classes/view/popup/StoreBagView.cpp \
../../IF/Classes/view/popup/StoreBuyConfirmDialog.cpp \
../../IF/Classes/view/popup/StoreMallCellTip.cpp \
../../IF/Classes/view/popup/StoreMallView.cpp \
../../IF/Classes/view/popup/StoreView.cpp \
../../IF/Classes/view/popup/SuggestionView.cpp \
../../IF/Classes/view/popup/TileOpenView.cpp \
../../IF/Classes/view/popup/TimeExchangeView.cpp \
../../IF/Classes/view/popup/TimeRwdShowView.cpp \
../../IF/Classes/view/popup/TipsView.cpp \
../../IF/Classes/view/popup/TipsWithPicView.cpp \
../../IF/Classes/view/popup/ToolCreateView.cpp \
../../IF/Classes/view/popup/TreasureMapView.cpp \
../../IF/Classes/view/popup/TroopsView.cpp \
../../IF/Classes/view/popup/UIComponent.cpp \
../../IF/Classes/view/popup/UpstarView.cpp \
../../IF/Classes/view/popup/UseBackpackItemView.cpp \
../../IF/Classes/view/popup/UseCDToolView.cpp \
../../IF/Classes/view/popup/UseCKFSkillView.cpp \
../../IF/Classes/view/popup/UseItemStatusView.cpp \
../../IF/Classes/view/popup/UseResToolView.cpp \
../../IF/Classes/view/popup/UserUpgradeView.cpp \
../../IF/Classes/view/popup/UseSkillPopUpView.cpp \
../../IF/Classes/view/popup/UseToolView.cpp \
../../IF/Classes/view/popup/VipActiveView.cpp \
../../IF/Classes/view/popup/VipConstants.cpp \
../../IF/Classes/view/popup/VipDetailCell.cpp \
../../IF/Classes/view/popup/VipDetailView.cpp \
../../IF/Classes/view/popup/VipUtil.cpp \
../../IF/Classes/view/popup/WaitInterface.cpp \
../../IF/Classes/view/popup/WatchtowerView.cpp \
../../IF/Classes/view/popup/WorldBannerRankView.cpp \
../../IF/Classes/view/popup/WorldBossMailView.cpp \
../../IF/Classes/view/popup/WorldBossRewardMailView.cpp \
../../IF/Classes/view/popup/WorldPopupOnceView.cpp \
../../IF/Classes/view/popup/YesNoDialog.cpp \
../../IF/Classes/view/popup/YuanJunTipView.cpp \
../../IF/Classes/view/skill/BaseSkill.cpp \
../../IF/Classes/view/skill/GongJian2.cpp \
../../IF/Classes/view/transition/TransitionCallback.cpp \
../../IF/Classes/view/Widget/IFCommonParNode.cpp \
../../IF/Classes/view/Widget/IFDailyActiveNode.cpp \
../../IF/Classes/view/Widget/IFFieldMonsterNode.cpp \
../../IF/Classes/view/Widget/IFHeiqishiNode.cpp \
../../IF/Classes/view/Widget/IFLoadingSceneArmyNode.cpp \
../../IF/Classes/view/Widget/IFNormalSkNode.cpp \
../../IF/Classes/view/Widget/IFSkeletonAnimation.cpp \
../../IF/Classes/view/Widget/IFSkeletonBatchLayer.cpp \
../../IF/Classes/view/Widget/IFSkeletonDataManager.cpp \
../../IF/Classes/view/Widget/IFSkeletonNode.cpp \
../../IF/Classes/view/Widget/IFWingNode.cpp \

